#!/bin/sh
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devpts none /dev/pts
#mkdir /mnt
#ifconfig lo 127.0.0.1
#telnetd
#mount -o nolock,rsize=1024 192.168.0.1:/rcu2 /mnt/
#dropbear
echo "Welcome to s2m-som Cortex-M3 Linux!"
